### ISSUE TITLE
Give some release?

### ISSUE THREAD

**Issue by Viky-zhang** [jubianchi/semver-check#30]
I want to run in local without Internet, I build it, but I got some errors like:
`npm ERR! Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.`

may be I was missing something needed, but If I can download from release, will save my time also.

Thx~

**Comment by jubianchi** [comment]
Hi @Viky-zhang!

Indeed, the errors says that something went wrong while building a node native extension. Your OS is probably missing a library or something.

BTW, you can download the prebuilt code at any time from [here](https://github.com/jubianchi/semver-check/archive/0d39fb70505ff77e1a89ab0bb6527dcbd35c9158.zip): the app is deployed using Github Pages so the production code is always available for download in the [`gh-pages`](https://github.com/jubianchi/semver-check/tree/gh-pages) branch ;)
