### ISSUE TITLE
Support Bundler's ~> Operator

### ISSUE THREAD

**Issue by codebycliff** [jubianchi/semver-check#31]
It doesn't look like the source code handles the case of [RubyGems' pessimistic operator](http://guides.rubygems.org/patterns/#pessimistic-version-constraint). This has lead to quite a bit of confusion as people are referencing this utility to check their `Gemfile` constraints. 

See the comments in this issue for more background on the confusion:

https://github.com/drapergem/draper/issues/808

**Comment by jubianchi** [comment]
@codebycliff Hi! thanks for your bug report.

I just deployed a new version of the app which adds support for the `~>` operator:

<img width="785" alt="capture d ecran 2017-06-28 a 22 55 38" src="https://user-images.githubusercontent.com/327237/27659793-0f9ea4a4-5c55-11e7-9573-b1d79e97e3fe.png">

Let me know if you find anything wrong.

Thanks again.
