### ISSUE TITLE
Any version satisfies a version constraint

### ISSUE THREAD

**Issue by Ricket** [jubianchi/semver-check#36]
Enter a version constraint like `1.0.0` in the constraint box. Now enter any version in the version box; `0.0.1` or `3.4.5` or whatever. All of them light up green with the "satisfies constraint" message.

I expected none of them to satisfy the constraint except for the exact version entered as the constraint. Am I incorrect?

**Comment by jubianchi** [comment]
Hi @Ricket!

Thanks for reporting this issue. It should be fixed now.
