### ISSUE TITLE
Equals is broken

### ISSUE THREAD

**Issue by RiotR1cket** [jubianchi/semver-check#40]
![image](https://user-images.githubusercontent.com/33143437/36695110-e6e75a40-1b05-11e8-8f02-fef642e19724.png)

**Comment by JeanMertz** [comment]
Here's another one that doesn't work:

<img width="744" alt="screen shot 2018-06-06 at 13 10 12" src="https://user-images.githubusercontent.com/383250/41034777-f80ad648-698a-11e8-9b89-ff3c95e7d483.png">
