### ISSUE TITLE
Does not handle prerelease versions correctly

### ISSUE THREAD

**Issue by rvandegrift** [jubianchi/semver-check#77]
Thanks for the online semver checker!  There appears to be an issue with prerelease version numbers.  If I enter the constraint `>=1.0.0`, the version `1.1.0-snapshot.1` does not match.

**Comment by dereuromark** [comment]
Same with any prelease (alpha, beta, RC) and two digits

![smver](https://user-images.githubusercontent.com/39854/88910634-0bcd0b00-d25d-11ea-96f5-40400a3787c4.png)

thats wrong, and I tested, composer works correctly here.

**Comment by jubianchi** [comment]
Thanks @dereuromark 

I'll work on fixing this in the coming days 😉
